# 基础配置：

# port: 7890                 #本地http代理端口
# socks-port: 7891           #本地socks5代理端口
# mixed-port: 7892             #本地混合代理(http和socks5合并）端口
# redir-port: 7893           #本地Linux/macOS Redir代理端口
# tproxy-port: 7894          #本地Linux Tproxy代理端口

# authentication:            # 本地SOCKS5/HTTP(S)代理端口认证设置
#  - "user1:pass1"
#  - "user2:pass2"


geodata-loader: standard
tcp-concurrent: true         #【Meta专属】TCP连接并发，如果域名解析结果对应多个IP，
                             # 并发所有IP，选择握手最快的IP进行连接
unified-delay: true


allow-lan: false                  #允许局域网连接(false/true)
# bind-address:                     #监听IP白名单（当allow-lan：true），只允许列表设备
  # '*'                             #全部设备
  # 192.168.122.11                #单个ip4地址
  # "[aaaa::a8aa:ff:fe09:57d8]"   #单个ip6地址

#  find-process-mode has 3 values:always, strict, off
#  - always, 开启，强制匹配所有进程
#  - strict, 默认，由 clash 判断是否开启
#  - off, 不匹配进程，推荐在路由器上使用此模式
find-process-mode: off

geodata-mode: true         #【Meta专属】使用geoip.dat数据库(默认：false使用mmdb数据库)
#自定义 geodata url
# geox-url:
  # geoip: "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat"
  # geosite: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
  # mmdb: "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb"
  


mode: rule                 #clash工作模式（rule/global/direct,meta暂不支持script）

log-level: debug            #日志等级（info/warning/error/debug/silent）

ipv6: false                #ip6开关，当为false时，停止解析hostanmes为ip6地址

# 配置 WEB UI 目录，使用 http://{{external-controller}}/ui 访问
# external-controller: 127.0.0.1:9093   #控制器监听地址
# external-ui: ./ui/                   #http服务路径，可以放静态web网页，如yacd的控制面板
# external-ui-name: xd                 #可通过`http://{{external-controller}}/ui`直接使用
# external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

# secret: ""                          #控制器登录密码

# 全局 TLS 指纹，优先低于 proxy 内的 client-fingerprint
# 可选： "chrome","firefox","safari","ios","random","none" options.
# Utls is currently support TLS transport in TCP/grpc/WS/HTTP for VLESS/Vmess and trojan.
# global-client-fingerprint: chrome

#  TCP keep alive interval
# keep-alive-interval: 15


profile:                   #缓存设置(文件位置./cache.db)
  store-selected: true    #节点状态记忆（若不同配置有同代理名称,设置值共享）, 存储 select 选择记录
  store-fake-ip: true      #fake-ip缓存, 持久化 fake-ip

# Tun 配置
tun:
  enable: true
  stack: system # gvisor / system / lwip
  dns-hijack:
    - 0.0.0.0:53 # 需要劫持的 DNS
  auto-detect-interface: true # 自动识别出口网卡
  auto-route: true # 配置路由表
  mtu: 9000 # 最大传输单元
  strict-route: true # 将所有连接路由到tun来防止泄漏，但你的设备将无法其他设备被访问
  # inet4-route-address: # 启用 auto_route 时使用自定义路由而不是默认路由
    # - 0.0.0.0/1
    # - 128.0.0.0/1
  # inet6-route-address: # 启用 auto_route 时使用自定义路由而不是默认路由
    # - "::/1"
    # - "8000::/1"


# 嗅探域名 可选配置
sniffer:                         #【Meta专属】sniffer域名嗅探器
  enable: true                   #嗅探开关
  ## 对 redir-host 类型识别的流量进行强制嗅探
  ## 如：Tun、Redir 和 TProxy 并 DNS 为 redir-host 皆属于
  # force-dns-mapping: false
  ## 对所有未获取到域名的流量进行强制嗅探
  # parse-pure-ip: false
  # 是否使用嗅探结果作为实际访问，默认 true
  # 全局配置，优先级低于 sniffer.sniff 实际配置
  override-destination: false
  sniff:                      #嗅探协议对象：目前支持tls/http
    quic:
    tls:
      # ports: [443, 8443]
    http:
      # ports: [80, 8080-8880]
      # override-destination: false
      
  # skip-domain:                   #列表中的sni字段，保留mapping结果，不通过嗅探还原域名
                                 #优先级比force-domain高
    # - 'Mijia Cloud'              #米家设备，建议加
    # - 'dlg.io.mi.com'
    # - '+.apple.com'              #苹果域名，建议加
  # - '*.baidu.com'              #支持通配符
    
  # force-domain:                  #需要强制嗅探的域名，默认只对IP嗅探
  # - '+'                        #去掉注释后等于全局嗅探
  # - 'google.com'
    
  #port-whitelist:               #端口白名单，只对名单内的端口进行还原域名
  # - 80.                        #已废弃，若 sniffer.sniff 配置则此项无效
  # - 443
  # - 8000-9000

# hosts:                           #host，支持通配符（非通配符域名优先级高于通配符域名）
  # '*.clash.dev': 127.0.0.1     #例如foo.example.com>*.example.com>.example.com
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'



# DNS配置：
# clash-for-android:
  # append-system-dns: false


dns:
  enable: true                 #DNS开关(false/true), 关闭将使用系统 DNS
  prefer-h3: true             # 开启 DoH 支持 HTTP/3，将并发尝试
  listen: 0.0.0.0:7884           #DNS监听地址
  ipv6: false                  #IP6解析开关；如果为false，将返回ip6结果为空
  
  default-nameserver:          #解析非IP的dns用的dns服务器,只支持纯IP
    - 114.114.114.114
    - 223.5.5.5
    - 223.6.6.6
    - 119.29.29.29
    # - 8.8.8.8
    
  nameserver-policy:                #指定域名使用自定义DNS解析
  # 'www.baidu.com': 'https://223.5.5.5/dns-query'
  # '+.internal.crop.com': '114.114.114.114'
    "geosite:category-ads-all": rcode://success
    
    "+.appcenter.ms": rcode://success
    "+.firebase.io": rcode://success
    "+.crashlytics": rcode://success
    "geosite:geolocation-!cn": '127.0.0.1:7884'
    "geosite:private,geolocation-cn": "https://223.5.5.5/dns-query"

 
  enhanced-mode: fake-ip          #DNS模式(redir-host/fake-ip)
                                     #【Meta专属】redir-host传递域名，可远程解析
  fake-ip-range: 198.18.0.1/16       #Fake-IP解析地址池
  use-hosts: true                  #查询hosts配置并返回真实IP
  
  fake-ip-filter:                  #Fake-ip过滤，列表中的域名返回真实ip
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time-ios.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - "+.pool.ntp.org"
    - time1.cloud.tencent.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - "+.qq.com"
    - "+.tencent.com"
    - "+.srv.nintendo.net"
    - "*.n.n.srv.nintendo.net"
    - "+.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - "+.battlenet.com.cn"
    - "+.wotgame.cn"
    - "+.wggames.cn"
    - "+.wowsgame.cn"
    - "+.wargaming.net"
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - na.b.g-tun.com
    - "+.nflxvideo.net"
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "*.ff14.sdo.com"
    - ff.dorado.sdo.com
    - "*.mcdn.bilivideo.cn"
    - "+.media.dssott.com"
    - shark007.net
    - Mijia Cloud
    - "+.cmbchina.com"
    - "+.cmbimg.com"
    - local.adguard.org
    - "+.sandai.net"
    - "+.n0808.com"
  
  proxy-server-nameserver:          #【Meta专属】解析代理服务器域名的dns
    - https://223.5.5.5/dns-query              # 不写时用nameserver解析
    - https://1.12.12.12/dns-query

  nameserver:                        #默认DNS服务器，支持udp/tcp/dot/doh/doq
    # - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
    # - https://1.12.12.12/dns-query#h3=true


    # - 8.8.8.8 # default value
    # - https://doh.pub/dns-query # DNS over HTTPS
    # - https://dns.alidns.com/dns-query#h3=true #【Meta专属】强制HTTP/3
    # - tls://223.5.5.5:853 # DNS over TLS
    # - https://mozilla.cloudflare-dns.com/dns-query#DNS&h3=true #【Meta专属】指定策略组和使用 HTTP/3
    # - dhcp://en0 # dns from dhcp
    # - quic://dns.adguard.com:784 # DNS over QUIC
    # - '8.8.8.8#en0' # 兼容指定DNS出口网卡
    
  # fallback:                          #回落DNS服务器，支持udp/tcp/dot/doh/doq
    # - 'https://1.1.1.1/dns-query#策略指向'
    # - 'tcp://208.67.222.222:443#策略指向'
    # - 'tls://1.1.1.1:853#策略指向'
    # - 'tls://8.8.4.4:853#策略指向'
    # - https://doh.dns.sb/dns-query
    
    # - quic://a.passcloud.xyz:784     #【Meta专属】Dns over quic
    # - 'tls://8.8.4.4:853#DNSg'       #【Meta专属】"#DNSg"代表该DNS服务器通过
                                     # 名为"DNSg"的proxy Group访问
                                     
  # fallback-filter:                   #回落DNS服务器过滤
    # geoip: false                      #为真时，不匹配为geoip规则的使用fallback返回结果
    # geoip-code: CN                   #geoip匹配区域设定
    # geosite:                         #【Meta专属】设定geosite某分类使用fallback返回结果
      # - geolocation-!cn
    # ipcidr:                          #列表中的ip使用fallback返回解析结果
      # - 240.0.0.0/4
    # domain:                          #列表中的域名使用fallback返回解析结果
      # - '+.google.com'
      # - '+.facebook.com'
      # - '+.youtube.com'


