---

allow-lan: true
bind-address: "*"
mode: rule
log-level: info
redir-port: 7892
tproxy-port: 7895
port: 7721
socks-port: 7857
mixed-port: 7668
secret: '98456'
external-controller: 0.0.0.0:8979
clash-for-android:
  append-system-dns: false
disable-stun: true
profile:
  tracing: true
  store-selected: true
ipv6: false
geodata-loader: standard
tcp-concurrent: true
unified-delay: true
find-process-mode: always
sniffer:
  enable: true
tun:
  enable: true
  stack: system
  device: utun
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://any:53
dns:
  enable: true
  prefer-h3: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  use-hosts: false
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - 223.5.5.5
  - 114.114.114.114
  - 119.29.29.29
  fallback:
  - https://1.1.1.1/dns-query
  - https://dns.cloudflare.com/dns-query
  - https://public.dns.iij.jp/dns-query
  - https://dns.oszx.co/dns-query
  fake-ip-range: 198.18.0.1/16
  enhanced-mode: fake-ip
  listen: 0.0.0.0:7874
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time-ios.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.qq.com"
  - "+.tencent.com"
  - "+.srv.nintendo.net"
  - "*.n.n.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.*.microsoft.com
  - "*.*.xboxlive.com"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*.*.*"
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - na.b.g-tun.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.ff14.sdo.com"
  - ff.dorado.sdo.com
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
  - shark007.net
  - Mijia Cloud
  - "+.cmbchina.com"
  - "+.cmbimg.com"
  - local.adguard.org
  - "+.sandai.net"
  - "+.n0808.com"
  - services.googleapis.cn

rule-providers:
  ChinaMaxNoIPv6:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Classical_No_IPv6.yaml
    interval: 86400

rules:
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- DOMAIN,epdg.epc.mnc240.mcc310.pub.3gppnetwork.org,DIRECT
- DOMAIN,epdg.epc.mnc260.mcc310.pub.3gppnetwork.org,DIRECT
- DOMAIN,ss.epdg.epc.mnc260.mcc310.pub.3gppnetwork.org,DIRECT
- DOMAIN,ss.epdg.epc.geo.mnc260.mcc310.pub.3gppnetwork.org,DIRECT
- DOMAIN-SUFFIX,xn--ngstr-lra8j.com,节点
- DOMAIN-SUFFIX,services.googleapis.cn,节点
- DOMAIN-SUFFIX,browserleaks.com,节点
- IP-CIDR,120.232.181.162/32,节点,no-resolve
- IP-CIDR,120.241.147.226/32,节点,no-resolve
- IP-CIDR,120.253.253.226/32,节点,no-resolve
- IP-CIDR,120.253.255.162/32,节点,no-resolve
- IP-CIDR,120.253.255.34/32,节点,no-resolve
- IP-CIDR,120.253.255.98/32,节点,no-resolve
- IP-CIDR,180.163.150.162/32,节点,no-resolve
- IP-CIDR,180.163.150.34/32,节点,no-resolve
- IP-CIDR,180.163.151.162/32,节点,no-resolve
- IP-CIDR,180.163.151.34/32,节点,no-resolve
- IP-CIDR,203.208.39.0/24,节点,no-resolve
- IP-CIDR,203.208.40.0/24,节点,no-resolve
- IP-CIDR,203.208.41.0/24,节点,no-resolve
- IP-CIDR,203.208.43.0/24,节点,no-resolve
- IP-CIDR,203.208.50.0/24,节点,no-resolve
- IP-CIDR,220.181.174.162/32,节点,no-resolve
- IP-CIDR,220.181.174.226/32,节点,no-resolve
- IP-CIDR,220.181.174.34/32,节点,no-resolve
- RULE-SET,ChinaMaxNoIPv6,DIRECT
- MATCH,节点
